#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Repeatable setup path for "Sign in with Google" (docs/hosting.md, "Google sign-in").
# Deliberately persists nothing: the Google client secret is shown by Google only once
# and lives on in Supabase (which stores it hashed); the Supabase token is yours. Both
# stay in this shell's memory for the one `auth-config` run. That is why this wizard
# never calls write_env / set_secret, unlike the template's example.

cd "$(git rev-parse --show-toplevel)"

# Defaults are production. Override to set up staging:
#   CLIENT_ORIGIN=https://castle-clash-staging.atomic-nucleus.com SUPABASE_PROJECT_REF=... ./scripts/setup-google-login.sh
CLIENT_ORIGIN="${CLIENT_ORIGIN:-https://castle-clash.atomic-nucleus.com}"
SUPABASE_PROJECT_REF="${SUPABASE_PROJECT_REF:-vrcxprhmonzpuelfnijy}"
AUTHORIZED_DOMAIN="atomic-nucleus.com"

banner "Castle Clash: Google sign-in ($CLIENT_ORIGIN)"

# ── 1. Consent screen: Branding ───────────────────────────────────────────
stage "Google Cloud: consent screen branding"
say "Google shows this to players. Nothing here needs Google's app review as long as"
say "you add no logo (a logo triggers brand verification) and ask for basic scopes only."
open_url "https://console.cloud.google.com/auth/branding"
step "Pick or create a Google Cloud project for the game (top-left project menu)."
step "If asked to get started: App name 'Castle Clash', your support email, audience 'External'."
step "Branding > App domain > Application home page: $CLIENT_ORIGIN"
step "Application privacy policy link: $CLIENT_ORIGIN/privacy"
step "Application terms of service link: $CLIENT_ORIGIN/terms"
step "Authorized domains > Add domain: $AUTHORIZED_DOMAIN"
step "Developer contact information: an email you read (Google writes here about the app)."
step "Do NOT upload a logo. Click Save."
warn "Have you read the privacy and terms pages? They are drafts; Google links to them."
pause "Saved the Branding page?"

# ── 2. Audience: publish ──────────────────────────────────────────────────
stage "Google Cloud: audience and publishing"
say "A 'Testing' app only admits listed test users. Publish it so anyone can sign in."
open_url "https://console.cloud.google.com/auth/audience"
step "User type should read External."
step "Publishing status > Publish app > Confirm. It must say 'In production'."
note "Google's docs say an openid/email/profile-only app is exempt from the test-user cap"
note "even in Testing, but that was not exercised; In production is the safe target."
pause "Status is 'In production'?"

# ── 3. Data access: scopes ────────────────────────────────────────────────
stage "Google Cloud: scopes"
say "Only the three non-sensitive sign-in scopes. Supabase asks for these by default."
open_url "https://console.cloud.google.com/auth/scopes"
step "Add or remove scopes. Select exactly: openid,"
step "  .../auth/userinfo.email and .../auth/userinfo.profile"
step "Update, then Save."
pause "Scopes saved?"

# ── 4. OAuth client ───────────────────────────────────────────────────────
stage "Google Cloud: the web client"
say "The one step no API or Terraform can do. Google shows the secret only once."
open_url "https://console.cloud.google.com/auth/clients"
step "Create client > Application type: Web application > name 'Castle Clash web'."
step "Authorized JavaScript origins > Add URI: $CLIENT_ORIGIN"
step "Authorized redirect URIs > Add URI (exactly, https, no trailing slash):"
step "  https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"
step "Create. Copy the Client ID, then the Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID (ends .apps.googleusercontent.com):"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret (hidden; kept in memory only):"
if [[ -z "$GOOGLE_CLIENT_ID" || -z "$GOOGLE_CLIENT_SECRET" ]]; then
  warn "Both values are needed. Re-run, and create a new secret in the console if you lost it."
  exit 1
fi

# ── 5. Supabase: what would change ────────────────────────────────────────
stage "Supabase: preview the auth settings change"
say "This turns on Google, guest-to-account linking, and the /auth/callback redirect."
say "It reads the live project first and prints a diff. Nothing is written yet."
if [[ -z "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
  SUPABASE_ACCESS_TOKEN="$(secret-tool lookup service 'Supabase CLI' username supabase 2>/dev/null || true)"
fi
if [[ -z "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
  open_url "https://supabase.com/dashboard/account/tokens"
  step "Generate a personal access token (name it 'castle-clash auth-config') and copy it."
  ask_secret SUPABASE_ACCESS_TOKEN "Paste the access token (sbp_..., hidden):"
else
  note "Using the token from your Supabase CLI login (or SUPABASE_ACCESS_TOKEN)."
fi
export SUPABASE_ACCESS_TOKEN SUPABASE_PROJECT_REF CLIENT_ORIGIN GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET

preview_status=0
pnpm --filter @castle-clash/server run auth-config || preview_status=$?
if [[ "$preview_status" -ne 0 && "$preview_status" -ne 2 ]]; then
  warn "The preview failed (see above). Nothing was changed."
  exit 1
fi
pause "Read the diff above. Continue to apply it?"

# ── 6. Supabase: apply and verify ─────────────────────────────────────────
stage "Supabase: apply the change"
say "Writes only the keys shown in the diff, then re-reads the whole config and fails"
say "if anything else changed. This is the LIVE project: $SUPABASE_PROJECT_REF"
if confirm "Apply to the live project now?"; then
  pnpm --filter @castle-clash/server run auth-config -- --apply
  say ""
  step "Then eyeball it once: Supabase dashboard > Authentication > Sign In / Providers."
  step "Google is enabled, and 'Allow manual linking' is on."
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
  step "Authentication > URL Configuration: Site URL is $CLIENT_ORIGIN."
  pause "Looks right?"
  say ""
  say "Last step is yours: run the real-Google checklist in docs/hosting.md"
  say "('Google sign-in: pre-release checklist') and record the result."
else
  warn "Not applied. Re-run this wizard when ready (Google side is already done)."
fi

unset GOOGLE_CLIENT_SECRET SUPABASE_ACCESS_TOKEN

finish
